# Generated by Django 4.1.7 on 2023-04-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_user_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='guid',
        ),
    ]
